server:
  port: 8080

spring:
  application:
    name: gateway-service
    
  # 本地开发环境禁用Nacos
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        
    gateway:
      # 禁用服务发现路由
      discovery:
        locator:
          enabled: false
      routes:
        # 用户服务路由
        - id: user-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_0_URI:http://localhost:8081}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
            
        # 图书服务路由
        - id: book-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_1_URI:http://localhost:8082}
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=0
            
        # 借阅服务路由
        - id: borrow-service
          uri: ${SPRING_CLOUD_GATEWAY_ROUTES_2_URI:http://localhost:8083}
          predicates:
            - Path=/api/borrow/**
          filters:
            - StripPrefix=0
            
      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false
            
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0

jwt:
  secret: library-system-secret-key-2024
  expiration: 86400

logging:
  level:
    com.library: debug
    org.springframework.cloud.gateway: debug
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always