server:
  port: 8080

spring:
  application:
    name: gateway-service
    
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service:8848
        
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
            
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=1
            
        - id: borrow-service
          uri: lb://borrow-service
          predicates:
            - Path=/api/borrow/**
          filters:
            - StripPrefix=1
            
  redis:
    host: redis-service
    port: 6379
    password: ${REDIS_PASSWORD:}
    database: 0

jwt:
  secret: library-system-secret-key-2024
  expiration: 86400

logging:
  level:
    com.library: debug
    org.springframework.cloud.gateway: debug