server:
  port: 8083

spring:
  application:
    name: borrow-service
  
  # 本地开发环境禁用Nacos
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 本地环境禁用Dubbo
dubbo:
  application:
    name: borrow-service
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  provider:
    register: false

logging:
  level:
    com.library: debug
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always